services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: troleum_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
    volumes:
      - ./json:/app/json  # Mount JSON directory for file persistence
      - ./static:/app/static  # Mount static directory for file persistence
