name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    container:
      image: golang:1.26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Show Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test ./app -count=1 -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage reports to Codecov
        # git ls-remote https://github.com/codecov/codecov-action refs/tags/v5
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          fail_ci_if_error: true
