name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    container:
      image: golang:1.26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Show Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test ./app -count=1 -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage reports to Codecov
        # git ls-remote https://github.com/codecov/codecov-action refs/tags/v7
        uses: codecov/codecov-action@a99c28d3f0da835de33ff2feb2e15691c7b9641f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          fail_ci_if_error: true

      - name: Install xz-utils for qlty upload
        run: |
          apt-get update
          apt-get install -y xz-utils

      - name: Upload coverage reports to qlty
        # git ls-remote https://github.com/qltysh/qlty-action refs/tags/v2
        uses: qltysh/qlty-action/coverage@08a0a862c159eae9b9003081da6663d96efef637
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ./coverage.out
          strip-prefix: troleum/
